---
- hosts: proxmox

  tasks:

  - name: Add an influxdb apt key
    ansible.builtin.apt_key:
      id: 05CE15085FC09D18E99EFB22684A14CF2582E0C5
      url: https://repos.influxdata.com/influxdb.key
      state: present

  - name: Install packages
    ansible.builtin.package:
      name:
        - vim-nox
        - tmux
        - hddtemp
        - lm-sensors
        - telegraf
      state: latest

  - name: Copy custom-metrics script
    copy:
      dest: "/usr/local/bin/custom-metrics"
      src: "files/custom-metrics"

  - name: Telegraf config
    template:
      src: "files/telegraf.conf.j2"
      dest: "/etc/telegraf/telegraf.conf"
    register: telegraf_conf

  - name: restart telegraf service
    service:
      name: telegraf
      state: restarted
    when: telegraf_conf.changed
